package com.catbit.mwckobweb.foundation.color

import org.jetbrains.compose.web.css.CSSColorValue

internal enum class ColorVariable(private val mdColor: String) : CSSColorValue {
    Primary("var(--md-sys-color-primary)"),
    SurfaceTint("var(--md-sys-color-surface-tint)"),
    OnPrimary("var(--md-sys-color-on-primary)"),
    PrimaryContainer("var(--md-sys-color-primary-container)"),
    OnPrimaryContainer("var(--md-sys-color-on-primary-container)"),
    Secondary("var(--md-sys-color-secondary)"),
    OnSecondary("var(--md-sys-color-on-secondary)"),
    SecondaryContainer("var(--md-sys-color-secondary-container)"),
    OnSecondaryContainer("var(--md-sys-color-on-secondary-container)"),
    Tertiary("var(--md-sys-color-tertiary)"),
    OnTertiary("var(--md-sys-color-on-tertiary)"),
    TertiaryContainer("var(--md-sys-color-tertiary-container)"),
    OnTertiaryContainer("var(--md-sys-color-on-tertiary-container)"),
    Error("var(--md-sys-color-error)"),
    OnError("var(--md-sys-color-on-error)"),
    ErrorContainer("var(--md-sys-color-error-container)"),
    OnErrorContainer("var(--md-sys-color-on-error-container)"),
    Background("var(--md-sys-color-background)"),
    OnBackground("var(--md-sys-color-on-background)"),
    Surface("var(--md-sys-color-surface)"),
    OnSurface("var(--md-sys-color-on-surface)"),
    SurfaceVariant("var(--md-sys-color-surface-variant)"),
    OnSurfaceVariant("var(--md-sys-color-on-surface-variant)"),
    Outline("var(--md-sys-color-outline)"),
    OutlineVariant("var(--md-sys-color-outline-variant)"),
    Shadow("var(--md-sys-color-shadow)"),
    Scrim("var(--md-sys-color-scrim)"),
    InverseSurface("var(--md-sys-color-inverse-surface)"),
    InverseOnSurface("var(--md-sys-color-inverse-on-surface)"),
    InversePrimary("var(--md-sys-color-inverse-primary)"),
    PrimaryFixed("var(--md-sys-color-primary-fixed)"),
    OnPrimaryFixed("var(--md-sys-color-on-primary-fixed)"),
    PrimaryFixedDim("var(--md-sys-color-primary-fixed-dim)"),
    OnPrimaryFixedVariant("var(--md-sys-color-on-primary-fixed-variant)"),
    SecondaryFixed("var(--md-sys-color-secondary-fixed)"),
    OnSecondaryFixed("var(--md-sys-color-on-secondary-fixed)"),
    SecondaryFixedDim("var(--md-sys-color-secondary-fixed-dim)"),
    OnSecondaryFixedVariant("var(--md-sys-color-on-secondary-fixed-variant)"),
    TertiaryFixed("var(--md-sys-color-tertiary-fixed)"),
    OnTertiaryFixed("var(--md-sys-color-on-tertiary-fixed)"),
    TertiaryFixedDim("var(--md-sys-color-tertiary-fixed-dim)"),
    OnTertiaryFixedVariant("var(--md-sys-color-on-tertiary-fixed-variant)"),
    SurfaceDim("var(--md-sys-color-surface-dim)"),
    SurfaceBright("var(--md-sys-color-surface-bright)"),
    SurfaceContainerLowest("var(--md-sys-color-surface-container-lowest)"),
    SurfaceContainerLow("var(--md-sys-color-surface-container-low)"),
    SurfaceContainer("var(--md-sys-color-surface-container)"),
    SurfaceContainerHigh("var(--md-sys-color-surface-container-high)"),
    SurfaceContainerHighest("var(--md-sys-color-surface-container-highest)");

    override fun toString() = mdColor

    companion object {
        fun toColorScheme() = ColorScheme(
            primary = Primary,
            onPrimary = OnPrimary,
            primaryContainer = PrimaryContainer,
            onPrimaryContainer = OnPrimaryContainer,
            inversePrimary = InversePrimary,
            secondary = Secondary,
            onSecondary = OnSecondary,
            secondaryContainer = SecondaryContainer,
            onSecondaryContainer = OnSecondaryContainer,
            tertiary = Tertiary,
            onTertiary = OnTertiary,
            tertiaryContainer = TertiaryContainer,
            onTertiaryContainer = OnTertiaryContainer,
            background = Background,
            onBackground = OnBackground,
            surface = Surface,
            onSurface = OnSurface,
            surfaceVariant = SurfaceVariant,
            onSurfaceVariant = OnSurfaceVariant,
            surfaceTint = SurfaceTint,
            inverseSurface = InverseSurface,
            inverseOnSurface = InverseOnSurface,
            error = Error,
            onError = OnError,
            errorContainer = ErrorContainer,
            onErrorContainer = OnErrorContainer,
            outline = Outline,
            outlineVariant = OutlineVariant,
            scrim = Scrim,
            shadow = Shadow,
            surfaceBright = SurfaceBright,
            primaryFixed = PrimaryFixed,
            onPrimaryFixed = OnPrimaryFixed,
            primaryFixedDim = PrimaryFixedDim,
            onPrimaryFixedVariant = OnPrimaryFixedVariant,
            secondaryFixed = SecondaryFixed,
            onSecondaryFixed = OnSecondaryFixed,
            secondaryFixedDim = SecondaryFixedDim,
            onSecondaryFixedVariant = OnSecondaryFixedVariant,
            tertiaryFixed = TertiaryFixed,
            onTertiaryFixed = OnTertiaryFixed,
            tertiaryFixedDim = TertiaryFixedDim,
            onTertiaryFixedVariant = OnTertiaryFixedVariant,
            surfaceDim = SurfaceDim,
            surfaceContainer = SurfaceContainer,
            surfaceContainerHigh = SurfaceContainerHigh,
            surfaceContainerHighest = SurfaceContainerHighest,
            surfaceContainerLow = SurfaceContainerLow,
            surfaceContainerLowest = SurfaceContainerLowest,
        )
    }
}