package dev.catbit.mwckobweb.foundation.color

import androidx.compose.runtime.Immutable
import org.jetbrains.compose.web.css.CSSColorValue

@Immutable
class ColorScheme (
    val primary: CSSColorValue,
    val onPrimary: CSSColorValue,
    val primaryContainer: CSSColorValue,
    val onPrimaryContainer: CSSColorValue,
    val inversePrimary: CSSColorValue,
    val secondary: CSSColorValue,
    val onSecondary: CSSColorValue,
    val secondaryContainer: CSSColorValue,
    val onSecondaryContainer: CSSColorValue,
    val tertiary: CSSColorValue,
    val onTertiary: CSSColorValue,
    val tertiaryContainer: CSSColorValue,
    val onTertiaryContainer: CSSColorValue,
    val background: CSSColorValue,
    val onBackground: CSSColorValue,
    val surface: CSSColorValue,
    val onSurface: CSSColorValue,
    val surfaceVariant: CSSColorValue,
    val onSurfaceVariant: CSSColorValue,
    val surfaceTint: CSSColorValue,
    val inverseSurface: CSSColorValue,
    val inverseOnSurface: CSSColorValue,
    val error: CSSColorValue,
    val onError: CSSColorValue,
    val errorContainer: CSSColorValue,
    val onErrorContainer: CSSColorValue,
    val outline: CSSColorValue,
    val outlineVariant: CSSColorValue,
    val scrim: CSSColorValue,
    val shadow: CSSColorValue,
    val surfaceBright: CSSColorValue,
    val primaryFixed: CSSColorValue,
    val onPrimaryFixed: CSSColorValue,
    val primaryFixedDim: CSSColorValue,
    val onPrimaryFixedVariant: CSSColorValue,
    val secondaryFixed: CSSColorValue,
    val onSecondaryFixed: CSSColorValue,
    val secondaryFixedDim: CSSColorValue,
    val onSecondaryFixedVariant: CSSColorValue,
    val tertiaryFixed: CSSColorValue,
    val onTertiaryFixed: CSSColorValue,
    val tertiaryFixedDim: CSSColorValue,
    val onTertiaryFixedVariant: CSSColorValue,
    val surfaceDim: CSSColorValue,
    val surfaceContainer: CSSColorValue,
    val surfaceContainerHigh: CSSColorValue,
    val surfaceContainerHighest: CSSColorValue,
    val surfaceContainerLow: CSSColorValue,
    val surfaceContainerLowest: CSSColorValue
)